### ISSUE TITLE
Request for Quantitative Evaluation Code

### ISSUE THREAD

**Issue by laura990501** [zichongc/DoesFS#3]
Thank you very much for sharing the code for "Deformable One-shot Face Stylization via DINO Semantic Guidance"! Your work is incredibly valuable to the community.

I was wondering if you could also provide the code related to the quantitative comparison metrics mentioned in the paper. It would greatly help in replicating the evaluation process and ensuring consistent results.

**Comment by zichongc** [comment]
I'm very sorry, but due to certain reasons, we do not intend to provide the code for the quantitative evaluation. However, if you need any help with the implementation, please feel free to reach out to me. :) 

chenzichong01@gmail.com
